# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pythonTestGUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from turtle import screensize
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_wndMain(object):
    def calculate(self):
        screen = self.lblNumber.text()
        try:
            answer = eval(screen)
            self.lblNumber.setText(str(answer))
        except:
            self.lblNumber.setText("ERROR")

    def press_it(self, pressed):
        if pressed == "C":
            self.lblNumber.setText("0")
        else:
            if self.lblNumber.text() == "0":
                self.lblNumber.setText("")
            self.lblNumber.setText(f'{self.lblNumber.text()}{pressed}')

    def setupUi(self, wndMain):
        wndMain.setObjectName("wndMain")
        wndMain.resize(800, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("I:/images/Bonk!_Atomic_Punch_item_icon_TF2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        wndMain.setWindowIcon(icon)
        self.cwiMain = QtWidgets.QWidget(wndMain)
        self.cwiMain.setObjectName("cwiMain")
        self.tbwMain = QtWidgets.QTabWidget(self.cwiMain)
        self.tbwMain.setGeometry(QtCore.QRect(0, 0, 781, 551))
        self.tbwMain.setObjectName("tbwMain")
        self.tbFirst = QtWidgets.QWidget()
        self.tbFirst.setObjectName("tbFirst")
        self.lblEntry = QtWidgets.QLabel(self.tbFirst)
        self.lblEntry.setGeometry(QtCore.QRect(30, 30, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.lblEntry.setFont(font)
        self.lblEntry.setObjectName("lblEntry")
        self.lntEntry = QtWidgets.QLineEdit(self.tbFirst)
        self.lntEntry.setGeometry(QtCore.QRect(30, 70, 431, 22))
        self.lntEntry.setObjectName("lntEntry")
        self.btnEntry = QtWidgets.QPushButton(self.tbFirst)
        self.btnEntry.setGeometry(QtCore.QRect(30, 120, 151, 41))
        self.btnEntry.setObjectName("btnEntry")
        self.btnEntry.clicked.connect(self.displayText)
        self.lblResult = QtWidgets.QLabel(self.tbFirst)
        self.lblResult.setGeometry(QtCore.QRect(30, 180, 701, 281))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.lblResult.setFont(font)
        self.lblResult.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lblResult.setObjectName("lblResult")
        self.tbwMain.addTab(self.tbFirst, "")
        self.tbSecond = QtWidgets.QWidget()
        self.tbSecond.setObjectName("tbSecond")
        self.btnOne = QtWidgets.QPushButton(self.tbSecond, clicked= lambda: self.press_it("1"))
        self.btnOne.setGeometry(QtCore.QRect(20, 80, 101, 51))
        self.btnOne.setObjectName("btnOne")
        self.btnTwo = QtWidgets.QPushButton(self.tbSecond, clicked= lambda: self.press_it("2"))
        self.btnTwo.setGeometry(QtCore.QRect(150, 80, 101, 51))
        self.btnTwo.setObjectName("btnTwo")
        self.btnThree = QtWidgets.QPushButton(self.tbSecond, clicked= lambda: self.press_it("3"))
        self.btnThree.setGeometry(QtCore.QRect(280, 80, 101, 51))
        self.btnThree.setObjectName("btnThree")
        self.btnFour = QtWidgets.QPushButton(self.tbSecond, clicked= lambda: self.press_it("4"))
        self.btnFour.setGeometry(QtCore.QRect(420, 80, 101, 51))
        self.btnFour.setObjectName("btnFour")
        self.btnFive = QtWidgets.QPushButton(self.tbSecond, clicked= lambda: self.press_it("5"))
        self.btnFive.setGeometry(QtCore.QRect(560, 80, 101, 51))
        self.btnFive.setObjectName("btnFive")
        self.btnSix = QtWidgets.QPushButton(self.tbSecond, clicked= lambda: self.press_it("6"))
        self.btnSix.setGeometry(QtCore.QRect(20, 165, 101, 51))
        self.btnSix.setObjectName("btnSix")
        self.btnEight = QtWidgets.QPushButton(self.tbSecond, clicked= lambda: self.press_it("8"))
        self.btnEight.setGeometry(QtCore.QRect(280, 165, 101, 51))
        self.btnEight.setObjectName("btnEight")
        self.btnSeven = QtWidgets.QPushButton(self.tbSecond, clicked= lambda: self.press_it("7"))
        self.btnSeven.setGeometry(QtCore.QRect(150, 165, 101, 51))
        self.btnSeven.setObjectName("btnSeven")
        self.btnNine = QtWidgets.QPushButton(self.tbSecond, clicked= lambda: self.press_it("9"))
        self.btnNine.setGeometry(QtCore.QRect(420, 165, 101, 51))
        self.btnNine.setObjectName("btnNine")
        self.btnZero = QtWidgets.QPushButton(self.tbSecond, clicked= lambda: self.press_it("0"))
        self.btnZero.setGeometry(QtCore.QRect(560, 165, 101, 51))
        self.btnZero.setObjectName("btnZero")
        self.btnDivide = QtWidgets.QPushButton(self.tbSecond, clicked= lambda: self.press_it("/"))
        self.btnDivide.setGeometry(QtCore.QRect(420, 250, 101, 51))
        self.btnDivide.setObjectName("btnDivide")
        self.btnMultiply = QtWidgets.QPushButton(self.tbSecond, clicked= lambda: self.press_it("*"))
        self.btnMultiply.setGeometry(QtCore.QRect(280, 250, 101, 51))
        self.btnMultiply.setObjectName("btnMultiply")
        self.btnMinus = QtWidgets.QPushButton(self.tbSecond, clicked= lambda: self.press_it("-"))
        self.btnMinus.setGeometry(QtCore.QRect(150, 250, 101, 51))
        self.btnMinus.setObjectName("btnMinus")
        self.btnPlus = QtWidgets.QPushButton(self.tbSecond, clicked= lambda: self.press_it("+"))
        self.btnPlus.setGeometry(QtCore.QRect(20, 250, 101, 51))
        self.btnPlus.setObjectName("btnPlus")
        self.btnEquals = QtWidgets.QPushButton(self.tbSecond, clicked= lambda: self.calculate())
        self.btnEquals.setGeometry(QtCore.QRect(560, 250, 101, 51))
        self.btnEquals.setObjectName("btnEquals")
        self.btnClear = QtWidgets.QPushButton(self.tbSecond, clicked= lambda: self.press_it("C"))
        self.btnClear.setGeometry(QtCore.QRect(20, 340, 641, 51))
        self.btnClear.setObjectName("btnClear")
        self.lblNumber = QtWidgets.QLabel(self.tbSecond)
        self.lblNumber.setGeometry(QtCore.QRect(30, 10, 741, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        self.lblNumber.setFont(font)
        self.lblNumber.setText("")
        self.lblNumber.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblNumber.setObjectName("lblNumber")
        self.tbwMain.addTab(self.tbSecond, "")
        wndMain.setCentralWidget(self.cwiMain)
        self.mnuMain = QtWidgets.QMenuBar(wndMain)
        self.mnuMain.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.mnuMain.setObjectName("mnuMain")
        self.mnuMenu = QtWidgets.QMenu(self.mnuMain)
        self.mnuMenu.setObjectName("mnuMenu")
        wndMain.setMenuBar(self.mnuMain)
        self.stbMain = QtWidgets.QStatusBar(wndMain)
        self.stbMain.setObjectName("stbMain")
        wndMain.setStatusBar(self.stbMain)
        self.actExit = QtWidgets.QAction(wndMain)
        self.actExit.setObjectName("actExit")
        #self.actExit.triggered.connect(self.quit)
        self.mnuMenu.addAction(self.actExit)
        self.mnuMain.addAction(self.mnuMenu.menuAction())

        self.retranslateUi(wndMain)
        self.tbwMain.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(wndMain)

    def retranslateUi(self, wndMain):
        _translate = QtCore.QCoreApplication.translate
        wndMain.setWindowTitle(_translate("wndMain", "Lee\'s Test UI (QT Edition)"))
        self.lblEntry.setText(_translate("wndMain", "Enter Text Below"))
        self.lntEntry.setText(_translate("wndMain", "Enter text here..."))
        self.btnEntry.setText(_translate("wndMain", "Parse Text"))
        self.lblResult.setText(_translate("wndMain", "Text to be displayed..."))
        self.tbwMain.setTabText(self.tbwMain.indexOf(self.tbFirst), _translate("wndMain", "Text Print"))
        self.btnOne.setText(_translate("wndMain", "1"))
        self.btnTwo.setText(_translate("wndMain", "2"))
        self.btnThree.setText(_translate("wndMain", "3"))
        self.btnFour.setText(_translate("wndMain", "4"))
        self.btnFive.setText(_translate("wndMain", "5"))
        self.btnSix.setText(_translate("wndMain", "6"))
        self.btnEight.setText(_translate("wndMain", "8"))
        self.btnSeven.setText(_translate("wndMain", "7"))
        self.btnNine.setText(_translate("wndMain", "9"))
        self.btnZero.setText(_translate("wndMain", "0"))
        self.btnDivide.setText(_translate("wndMain", "/"))
        self.btnMultiply.setText(_translate("wndMain", "*"))
        self.btnMinus.setText(_translate("wndMain", "-"))
        self.btnPlus.setText(_translate("wndMain", "+"))
        self.btnEquals.setText(_translate("wndMain", "="))
        self.btnClear.setText(_translate("wndMain", "C"))
        self.tbwMain.setTabText(self.tbwMain.indexOf(self.tbSecond), _translate("wndMain", "Calculator"))
        self.mnuMenu.setTitle(_translate("wndMain", "Menu"))
        self.actExit.setText(_translate("wndMain", "Exit"))

    def displayText(self):
        self.text = self.lntEntry.text()
        self.lblResult.setText(self.text)

    def clearText(self):
        self.lblNumber.clear()

    def _connectActions(self, wndMain):
        self.actExit.triggered.connect(self.close)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    wndMain = QtWidgets.QMainWindow()
    ui = Ui_wndMain()
    ui.setupUi(wndMain)
    wndMain.show()
    sys.exit(app.exec_())
